/**
 * (FOUNDATION04 PHASE A — WRITER-HELPER-TEARDOWN-
 *  OUTCOME01-CORRECTION01-MICROFIX01)
 *
 * Cross-test teardown-outcome registry. Stores the
 * typed `TerminateOutcome` for each writer child
 * that has been torn down during the live lane,
 * keyed by a stable process-lifetime identity.
 *
 * Why identity-keyed (CORRECTION01-MICROFIX01):
 *
 *   `runDir` is contextual identity — the directory
 *   persists across writer restarts. The harness
 *   exercises writer A → stop → writer B against
 *   the SAME runDir (see LWQ07 / LW-LIVE09/10 —
 *   restart preserves dedup state). Under a
 *   `Map<runDir, TerminateOutcome>` the second
 *   writer's teardown OVERWRITES the first writer's
 *   evidence. Worse, residue joining later by
 *   runDir alone can attribute the second writer's
 *   teardown cause to the first writer's
 *   observation (or vice versa).
 *
 *   Per Factory's lifecycle rule:
 *
 *     process-lifetime evidence MUST be keyed by
 *     process-lifetime identity
 *
 *   The lifetime identity we use here is
 *   `WriterLifetimeId`, an opaque branded token
 *   minted when the helper starts the writer.
 *   This is NOT the child's PID — Node explicitly
 *   warns that PIDs can be reused. It is a logical
 *   per-incarnation handle, generated by the
 *   fixture itself, with no observable on the
 *   kernel side.
 *
 *   The (runDir, lifetimeId) pair together binds:
 *
 *     logical run context  + specific incarnation
 *
 *   which is what the residue sweep needs to join
 *   cause (typed outcome) with effect (residue
 *   observation) without cross-attribution.
 *
 * Concurrency:
 *   Node's single-threaded event loop guarantees
 *   that mutations between `await` points cannot
 *   race. Map access is fine for test-fixture
 *   semantics.
 *
 * Lifecycle:
 *   Module-scope state. Test setup calls
 *   `clearWriterTeardowns()` before each
 *   adversarial run (see WSTOP11).
 */
import type { TerminateOutcome } from "./_writer_teardown.js";

/**
 * Opaque process-lifetime identity. Minted once
 * per writer incarnation inside the helper.
 *
 * Branded via `unique symbol` so the type system
 * refuses accidental interop with arbitrary
 * strings. The `__writerLifetimeId` brand has no
 * runtime representation; it is purely a
 * compile-time fence.
 */
export type WriterLifetimeId = string & {
  readonly __writerLifetimeId: unique symbol;
};

/**
 * Counter-backed mint. We avoid `crypto.randomUUID`
 * here to keep the oracle outputs deterministic;
 * uniqueness within a single test process is
 * guaranteed by monotonic increment + pid.
 */
let lifetimeCounter = 0;

export function makeWriterLifetimeId(): WriterLifetimeId {
  lifetimeCounter += 1;
  const raw = `lifetime-${process.pid}-${lifetimeCounter}`;
  // The cast is the single point where the
  // branded type is minted. No other site in the
  // codebase is permitted to perform this cast.
  return raw as WriterLifetimeId;
}

/**
 * Snapshot of a recorded teardown. The `key` is
 * the WriterLifetimeId — process-lifetime
 * identity, NOT the runDir.
 */
export type TeardownRecord = {
  readonly key: WriterLifetimeId;
  readonly outcome: TerminateOutcome;
  readonly recordedAt: number;
};

const teardowns: Map<WriterLifetimeId, TeardownRecord> = new Map();

/**
 * Record the typed teardown outcome for a writer
 * child, keyed by its lifetime identity.
 *
 * This is the SOLE point at which a typed outcome
 * becomes part of the cross-cutting residue
 * evidence. Per CORRECTION01 evidence-propagation
 * doctrine, the recording happens INSIDE
 * `WriterHandle.stop()` so the caller cannot
 * forget.
 */
export function recordWriterTeardown(
  key: WriterLifetimeId,
  outcome: TerminateOutcome,
): void {
  teardowns.set(key, {
    key,
    outcome,
    recordedAt: Date.now(),
  });
}

/**
 * Look up a previously-recorded teardown outcome
 * by lifetime identity. Returns `undefined` if no
 * teardown was recorded for the given key.
 */
export function getWriterTeardown(
  key: WriterLifetimeId,
): TeardownRecord | undefined {
  return teardowns.get(key);
}

/**
 * Snapshot all recorded teardowns, keyed by
 * lifetime identity. The sweep uses this to join
 * cause (typed outcome) with effect (residue
 * observation) per-incarnation.
 */
export function getAllWriterTeardowns(): readonly TeardownRecord[] {
  return Array.from(teardowns.values());
}

/**
 * Number of recorded teardowns. Used by WSTOP11
 * to assert registry reset discipline.
 */
export function writerTeardownCount(): number {
  return teardowns.size;
}

/**
 * Clear the registry. Used by test setup to ensure
 * each adversarial run starts from a clean slate
 * (WSTOP11). Mandatory before and after each
 * qualification lane run.
 */
export function clearWriterTeardowns(): void {
  teardowns.clear();
}

/**
 * Reset the lifetime counter. Used by test setup
 * (WSTOP11) to keep oracle outputs deterministic.
 */
export function resetLifetimeCounter(): void {
  lifetimeCounter = 0;
}
