import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
const fixturesDir = "/Volumes/UserData/Users/chistyakov/Projects/SPbNIX/factory/labs/long-horizon-harness/lifecycle-corpus/fixtures";
function w(rel, content) { const abs = resolve(fixturesDir, rel); mkdirSync(dirname(abs), { recursive: true }); writeFileSync(abs, content); }
const GATE_STARTED = (id, att) => ({ type:"GATE_STARTED", gate_id:`gate:${id}`, attempt_id:att });
const GATE_FINISHED = (id, att, pass, reason) => ({ type:"GATE_FINISHED", gate_id:`gate:${id}`, attempt_id:att, pass, ...(reason!==undefined?{reason}:{}) });
const RUN_CANCEL = (reason) => ({ type:"RUN_CANCEL_REQUESTED", ...(reason!==undefined?{reason}:{}) });
const RUN_FINISHED = (semantic, claimed) => ({ type:"RUN_FINISHED", semantic, ...(claimed!==undefined?{agent_report:{message:claimed, claimed:claimed}}:{}) });
const RUN_ABORTED = (semantic, reason) => ({ type:"RUN_ABORTED", semantic, reason });
w("lc01-canonical-success/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc01-001"),GATE_FINISHED("g1","att:lc01-001",true,"smoke_passed"),RUN_FINISHED("SUCCESS","done")])+"\n");
w("lc02-premature-done/phase_e_oracle.json", JSON.stringify([])+"\n");
w("lc03-gate-fail-then-done/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc03-001"),GATE_FINISHED("g1","att:lc03-001",false,"tests_failed"),RUN_FINISHED("SUCCESS","done")])+"\n");
w("lc04-ineffective-repair/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc04-001"),GATE_FINISHED("g1","att:lc04-001",true,"initial"),RUN_FINISHED("SUCCESS","fixed")])+"\n");
w("lc05-malformed-native/phase_e_oracle.json", JSON.stringify([])+"\n");
w("lc06-context-pressure/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc06-001"),GATE_FINISHED("g1","att:lc06-001",true,"smoke_passed"),RUN_FINISHED("SUCCESS","done")])+"\n");
w("lc07-restart-recovery/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc07-001"),GATE_FINISHED("g1","att:lc07-001",true,"done"),RUN_FINISHED("SUCCESS","done")])+"\n");
w("lc08-cancel-request/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc08-001"),GATE_FINISHED("g1","att:lc08-001",true,"half_done"),RUN_CANCEL("user_requested"),RUN_ABORTED("CANCELLED","user cancelled")])+"\n");
w("lc09-dependency-failure/phase_e_oracle.json", JSON.stringify([RUN_ABORTED("HARNESS_FAILURE","dependency unavailable")])+"\n");
w("lc10-destructive-attempt-denied/phase_e_oracle.json", JSON.stringify([])+"\n");
w("lc11-evidence-corruption-handoff/phase_e_oracle.json", JSON.stringify([])+"\n");
w("lc12-terminal-disagreement/phase_e_oracle.json", JSON.stringify([GATE_STARTED("g1","att:lc12-001"),GATE_FINISHED("g1","att:lc12-001",false,"external_gate_failed"),RUN_FINISHED("VALID_FAILURE","done (harness said)")])+"\n");
console.log("LH-05 phase_e_oracle fixtures written");
